# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"/\n\tOrderItem\x12\x10\n\x08offer_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"F\n\x12\x43reateOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1f\n\x05items\x18\x02 \x03(\x0b\x32\x10.order.OrderItem\"T\n\x14UpdatePaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\npayment_id\x18\x02 \x01(\x05\x12\x16\n\x0epayment_status\x18\x03 \x01(\t\"^\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x12\n\npayment_id\x18\x02 \x01(\x05\x12\x16\n\x0epayment_status\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\x32\x92\x01\n\x0cOrderService\x12>\n\x0b\x43reateOrder\x12\x19.order.CreateOrderRequest\x1a\x14.order.OrderResponse\x12\x42\n\rUpdatePayment\x12\x1b.order.UpdatePaymentRequest\x1a\x14.order.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERITEM']._serialized_start=22
  _globals['_ORDERITEM']._serialized_end=69
  _globals['_CREATEORDERREQUEST']._serialized_start=71
  _globals['_CREATEORDERREQUEST']._serialized_end=141
  _globals['_UPDATEPAYMENTREQUEST']._serialized_start=143
  _globals['_UPDATEPAYMENTREQUEST']._serialized_end=227
  _globals['_ORDERRESPONSE']._serialized_start=229
  _globals['_ORDERRESPONSE']._serialized_end=323
  _globals['_ORDERSERVICE']._serialized_start=326
  _globals['_ORDERSERVICE']._serialized_end=472
# @@protoc_insertion_point(module_scope)
